#pragma once

// Generated from the previously embedded Font Awesome 7 Solid font.
// Keep glyph declarations and ranges in ui_icons.h in sync with this subset.
namespace FontAwesome7Data {
inline constexpr char kSolidCompressedBase85[] =
    "7])#######L:`o]'/###Kn6+>%epo%Ql#v#haKT9wg'EYeo+##sh(##lCue=D/YIbY^'##Tet9);vA0F2%$-aPT&##]v&##l?>UCevMh;u='##h>f--f'TqLk6ZJCL=n922)[w'B3n0F"
    "0/3nLB3S>-?2.Q/]J[^Ia8]d<&`O&#o/7m/g=00FpSLYMO2jq/^?uu#X&S+H$uqtLh'OVRtnNw9Ak%##sDDF6);5##<H-)*g$fFH`RM*HGlAh4-]7V1g`'oD,::V%*:648`RJE#k5=$#"
    "Zk>`sSvJL9E$cY+*joY,P3,2']X/`=h7?nOE/AT%8[)^OGA&AEE6f.0m(3L+,9'V0;2n$XM[_c*`)0=Y7j&kLP$/-#EXI%#v>$(#P%T*#+b.-#[G_/#6.92#gji4#APC7#r6t9#LsM<#"
    "(](?#W?XA#2&3D#cbcF#=H=I#n.nK#HkGN##QxP#S7RS#4[[[#:V/a#r20iFsN@qC<XWeNiu=G4e(H<-g.dW-#`/`&7$0FOjIRA-7aU[-@;UF..Beh2S[V,3IZ@.6[;>)4xiB,3)Av`4"
    "nSgG3a(H<-a%H<-`H>-O[lZL22_n*.Abs*Oujmh2F(2g2vfR2.DwJFO-9H`-@?+:i5)gb4wd3g2cqAN-T9H`-)jQRa73T+Oo[4(56xVA51xZp0_/WI3S(*M-H8hK-quxb-E<4:iFL3u7"
    "M*oJ3noO`>->hoDY,>&5F97L2EsEM26rn@-pxtLFEf)NV6t'vH:-1`5.<7L2C`dT8DX=gG&>.FHMeZ<0/])'P/f*A-v;+G-g`'oD`eVIMN5J-#WF0DNrvg^#B6]uG1[^Y5w4xFrS:;)<"
    "te+#Yw&x>#cE'gUe@<N'k-W5S_hIa<QRN^=,/UQ/B`EaWd6)_+2iW<?RuDh1)#A3p(qPb3b$.CO0keX-6wMSc0@c[+48l-$uYmbVA9Fl)sBuUM3VDbtNebb)j[w<m]N(aODtB,M?Ac$M"
    "&]8+M^nl-M*7S`tdbX_O]Vm6Xdld0^;]&oO6wqLG=9P%4EAY(IH[Gc%jvkU%h73fHSP>f%6$8]$BjSnR&vS_OQ+v)JgU7jO#,K(J<3G%49=wbO6L`9.QrJWU3i>X(lpc`O*4[NUnx`mO"
    "L>VRs,Hi*MWnudMZl?2M&]kQ'x?KbMHZOvJh8__%<BP+)uxjjOK:'b%$])jO=Qu]tEXaX$1(tvJnJME/xetWn0'=gL4CcSn8(=gL9S(?%Q6?bO*Jp]th]Yg)xjIMet):^OQ<N56(5XcO"
    "+d].6iW*>e3IKc%N*l6euB$+NMXnuLp64kO847:M7n;o.ideCGeAnUMgnKb%?I[uL:L]Ds1rHW$pr9S-GP4U%fPqb%]suPOFk]Dso'DDsx:H8R`]R+R5vVJQf`wbRTbM3kBNIDsSnifQ"
    "cSebRx:tVMwBQc%S)6i$1kPZ$Kb-.:.7&4T+/pVL9cwnRI.'dM4rhtLm'fNOKgCeQ3M#FsT:%$T)IZ&TPrn;V$71b%6o=DsvGPn$,c=kPTYBN'aM++;O&v&T=0Ic%lX_MT1ri[%l2_2T"
    "7,csMZ0XvLL8mh$o,qsM<vg>Y;nd]K(#cWL8*Ia$CLwUMqu6^OW)kDWOT.aaHQ8ZL.&>[KJQr`$'A_pM*5Rj9wu#tL(VhpMHk#_$(s=<L-xFa<fXIjOZ1B@T*ctm$DZCER1ARj9K1v5N"
    "MVW$T^p$l$kwu=Uo>J&bVQVFR`VeFR,1D2P36<d%dOG/LrITHR-NtUaDA`#U3hqb%YPbPS(xGAT(2[&gstCCj+n`F[tb.h%(@nB[vS4QA_^AhOv3.`A(AppOj,%30'@hk)>U3jO%_t]t"
    "RNBb$-G>@Kw@j;QVcN$T3#nmOIoO19p*b-Y>]c2`7PqoOY8D+[HV+19H8)21s4'HR94k;Q_EkvLL;>W/?YfJCVklwYvD59.d'1c)L]LSoq#08%f1ers.4Vh)jZ3i0uG.iOiYH`%(gcC3"
    "#(/rJxpDd%aF#]TM'^Ds-j%]$uO>xT-io`ts82[$:0=oT?XGpRsx*cRZZLr$i3V_Oq&n]OQce=Mg[bF+1vvmOZk[#LCqw`tdmlkGL]RfG=@r_t'?OfG)DOlWCX`Gsd1`^SmqY=UVqKr)"
    "e>Di8j(SZ7FYM-2;:`k)eeMf$r$@W^8JL<q^Vt]Oh_asatQm<ca'gs-eMs]O`d6aI/eg=:@W^@TX@Oa%#E8?KFl%EEe%31^2?WR8Fp8WRaQSFeWao*%l]v0K.c?BSg;*O=)fIf$uIpDS"
    "0`7^OQO7^K5k7+Mh+gjO.c(]K'cqj)'/#[1Z@d<e#DGIDmG,iOqbnktKva8^VsusO'uog%7^6vZ%,XqLCIB40;44CXQewiOg=x/NP2<iOm,kOXSXgXV,g.bR,J)V$@XeFRr6Ub%,#QZ$"
    "E=@uLiPuDN4rhtLoEUj00*'gLJ0KSN/H;FRh%=GR%s&o$hY7/Q3+g8RY#DIQg]i[C<R2q$jl[JQ(2`,D:a`ks8+koVVWlcHmbqc$8-PDWeZOtVvRpoVGrDh$LJT=GvG<RNfnKb%QUr`N"
    "GQ(eQsW]VMeD.jPjRai$hVRJQFq]Ds7,J]$;B]]t;8J]$as9k)qpqvACB5^ODBr]OQVQjat<vWRUNiqO2[.oaR)bp$1q&X-3P>mUs[8+MpM8jOn1G[$QTANU*;/nOR^Of$[TuT%qoHf$"
    "@6Zxs$5-*R.iC9M^g6UM^Xta%`d-W$>4r]K4:(QSe='`SEt(UmZ3&mSn`VmOAJt[TPg(*Rh(jt(/@+c2w`@i)/Ojq-IilNX2cu]OQR:2XdDxrOP]rUVSP>f%=*AU)b9#pVsIj,;vu@UH"
    "s,Vt76[2Gs9<Ap7a@VDFh#15%R2uOF;uh;-o8u<%[tQ^t6)Q_Em/jjOd-(b%k[V=>56>9V<sad%)+V:V?Tu]tFV4^$)15)Nq<W^S$>#wK*WK[0Q_=Gs%FnA-HN3^-dp<:)kx6*I#'ad%"
    "1j/Z.T0^DsADnA--15)N2#;aSg*]#LTIDZ5bH[Ss$4okt`f'<-)oDc%fe`'R,Wu]tb/`JL=O3VM+-Z*Rj4XcR*P>p$#r/p`Y09^O2+VR%@;i*MXUaJ1t%g=#vI5V%H8Wr)LF8jiT8RtL"
    "$8fn$jiHf$E6,LPP8h/C:kPER;_ajO'jb`O8(AV%c7[sf[wQ^tE,fdsawb0lK+4[$l(Cp7m3fp]fYnkt;?2<^V;=,N6xh,1(..FR)tHc%fJ.jP:YlPo+BZp0rXE<BQp.[t*.0$85pwm0"
    "Q2L-2hI;=>8x6<-duV^%FTICfADp]O`*o^K-]WIbf5DaJv4,kbI;Hf$CW1c)k?amTY$Jf$+@X]tN(4aOP(%jTLKK;e]v?uLx;;v-q[wEIPLe^SqAlBM&BB;M)ZckOj>Ah)n8/Z$BEKp."
    "X@Oa%4KFN;fdbg$vpuXU2i=m$`#C%4qhK1Y8/`_%I/mLF2P)HD7M_29`6=Q'v96brlQccsAlUE5&cA+Mo#_H%ChUbIV%Xcsig>69kUV+7w9<i5N(N-2ZaPOA7`P-QVIta%dZ*a$&`Hf$"
    "dNt;Mu=j;Q(>PWL_.31^(P*jK+V:xK)wcaRpn5ATVONU?$?b$0VifjOUij$T/[n/QEZEd%LnObMD5;#U'FLb%UKxHs9@J#*:wj8.*/D%4OADn/[EpY$VxAu,4Ns'%nl1T.&mu$4bR3^-"
    "s0>ZIWt$78>ct05Z0.C8-lPHMmg=9[ArKK*<]OO85AWVRY(v;-kvkU%M%ek)IxfSRQ9KkOOKuREf,%UMi<Hc%L)'gLQdulOL9B.Z0nE,R3tHc%_F6d)1x$:3:6<Ds#Ru].]f%FsP%'N-"
    "F>,=Qvp/[sD9F#M#uO?NOq5[j1gQf.F/p?kt'EJ'&]D9../D%4uX.U.[?gY$xwU5/v5peU^>9a8:GJ`t>RIQ8hxKR'fhdk)k5WRs`w1^OrQ>gLp[8+MnL>r-<ij-$G#p]t4J<+MxI>r-"
    "*.TgLOqJ)a&s=_to$kSIQrJ-R0;TXsph%GRkY%jPb&7ab?[GhLou?^='-r`N3rq9MRk.#goT8;7piYX>i99gH^=Bb%5OK5J)f2jOS'Y(/dR#a$nJ<'JmuB80m7UASoQCb%T,>/Uo*Z=U"
    "dMi@ajg)a$ggp<MZdn_`FvgDSI&Te%-Nu]O[U`EJ]wr-a(d6*M'K1tUr^I^47v>ftJ+Bf-e9LFOM?pOO7#ZUr+<2l$7ITr)IUIuL>K3^On?P*OI0^OOlh5a$NE,lO'C?T/wgZ]t;:<m)"
    "7gx/2Uxuqr0.v<-tIOV.pF%wY<6hl'tBOf$ICiIIfcd;Z833bS6-L_E*Pm<-5W5L1YYW7V6c`)Ekj7vK>i>+#=G_t'Soqu:4bWY:*@Jf$kHL`t1vv`O+[IY:TU'GR87v?.$RxCP/+tG5"
    "(8#v)iUdk$uqpDS=XCmSQ-'kO1cnktB>aEck9eQ%T.gA;tg%p]0n^H4sGEIhY5.#%8*S_O^MR#%oWFIsoQd:;j*.6%l/][g@lP?n:i4L<gvVGW&lUe4xF$:;,T<X(,uKB;e'^/-iMl8."
    "&&61'XKEwK^*rgL2QXQ'-F#FslAcsO`vQ%9MGJH=M+Fc%YBJf$`N=+ckd9^OR+vbg1Ri*MTj0=>)vS_OQ>Ro-la-[-OC#cONWAf-a?T'NDOLwOih'rrxU'x5#vvr.n#0is$2>H7;8/Is"
    "#CLbaQxYgOd79i>q6QfOX(9ekV`xn$a'e0^4ifUH75VRs04F$Mr*:m$a^<;&V?9'ZEEo>-0.$t$2e(gL(mmF@uMh&*>9mhL[%*V;,ZSq)$D:aN#NM-2*n@C<MjGaSnmjZp;TGf$cEXvL"
    "#c+TRl_b0Nw0?=&EsOn(*JWf%4I9i$u7#g)10fu-]e(J8w3S`t1PUX%;2r<cC7jw7S8S`tEc8<(tjWeFt*:wOIQPQ';xF$*o$r^o+A)T.@&r]ODQ:92^)DMPAh]DsLL6vPaA%JQ$L@p&"
    "J=7<-J%e=.QFom>e0kG;xpMGs+l.+<Kr]'-'^pW$2qR_OABKSoL'pC%@_/S'cj@=>E8:lF8/`_%pojX$-2tRFoHF_$YJDT%m^jci7;vkEcM8kOj?Lb%a8imO)44jg%BxcRbD.bRGj.n$"
    "AeWjObDY)N)aUrE4H@6sKHKi:hwa>-h66]%[w`aOa2Kmt6c7bO^s$YL;Qjd%?fDDs6([W$a?jI1GKg)S<-Ic%OXN#./*,dNtkQ^tNQ9F50,_e$&HfER[dlF,oBpg8u+0kO'@gC/1O$gL"
    "/x?uLVt[#%KThi$J]q[-9=O&d+Ra;;t2:BY*ugWM4'ad%B4<M-Du;M-eMo+/`YeMKa$ALY$KeKYV1ersD_@i)-h;#(nq2e4#XDb$*gW/H:'S)W0_BGHGO+WLFf[`%A[9I4GZ6/<jpVW["
    ",I.jP79*d%=S4@@kSW8_sCpoN49Ed%;]388X7aVR^hgS%jRw/M:1[qM3#=Q;*a9N_HQorMC:@uLA]b)P=?RF'@DK5T(/p-?#9iQWbHq;Hfjt9WNJ?*STD,f%[UO,;fu@nj$8If=cqfV/"
    "(C:W)7d=%#.[ZC#Qf./LFJ%mGafts'alVP&S9w0#k1[w:+7Vp.+H-JLV'LR*&;+GML7$##*'o-$^h)##UNj-$o39`&3rbA#S-6F%P'dA#W'l-$8bD[K<Xv--apdF%2dm-$Lv0`/&#jkF"
    "Oo#F@4(cA#R*H&#G#&B#ckh3=.)<X(V9Cn#%9)=-,1il/PM(Z#UH*1#)Y>W-R3n0#aE?GMlH-##ln+GM'ocW-rOSq)1'O2(:1p*%89ff=7N3<qZbgdMkY@`a(O;uM+;>GMRS5;-Fnc&#"
    "#.qdM=rY<-85T;-%lL5/$),##-X6iL-oP<-GwhH-a@`T.D-4&#brG<-N2:W.ZP?(#:4xU.>L7%#aA`T.Y,_'#vA`T.EXI%#LB`T.E:r$#`tG<-<5]^.+MC;$@+uC.I'a<#.(1B#$_ro."
    "01L^#.H5>>1:h#$k9GPA.+_>$O?IZ$$'TiT@$ev$NUHuu8$&9&QV>209-AT&*IBJL>Zt2(Nv%8[;KkM(9_bP2M4`.*H$Bp.;<7L2<?er^7L^S)vt/PD0:rVC@rLG-=C=GH>_V.G.gcdG"
    "*M#hF5xLVC2]HKF6-giF)QtnDM<,FHa9if5WZ<hFnXFB@6REj1<QI7M]'2X%__tc<H'FP8XhdxFeBEYGIYo+DUw%;HlBel/Zl,20itbP9OpMDFv3gs7Ur8JC(m_w':h/F%jXk>-hdg34"
    "bwi9;<n/F%Fq8X12&%L>2)b%O5XAA-G'm@.,E-(#vMk]>]Zi]G^'ufD.C>?-?%4>5Lp)4+S,;D3VdaJ2]2T,3TpK'J[Yh1TX?8/PE%[lL,%wLMbJr'#Q,&_NNE*q-_fKwgp[kedW#4GD"
    "1Em>-xsNe$$WKP/*1p>-W:`?T-C&;H4+1&GG&x&GZUL`ELODYG@*-gDn1(@^i8q92M$g5BKMs.CSJF>HLmi`FZ/eGEHu*L5IkxK>A'0F%0Q,R<Y&$,2-.tiCtOG>HZh+QLVC$LME2dXT"
    "4wN(&r9w0#I)###VWj-$_%vu#Z,>F%Zq4/(P82N9NPj)#oHP.qcB:/q$<[0qq?85qAEl6ql7X9qHpZCqA3*Dq)GVcqxM*LqCABMq_d'^q'f7)r[]LnqJ2XtroV0#te_>]O58hKMnuQ6q"
    "g%4B-o$4B-eb3B-a1QZ%f0gi'8_8.(fY0+()0r((iBc'(r]^#(2T#r'd1Cn'+6;O'0HCA4^N@d'=I3T'8g%5'EE1V&m*wg%;sebMXr@&`eCT<&Q>;AttWE_G";

} // namespace FontAwesome7Data
