#pragma once

// Generated from Font Awesome 7 Free Solid webfont.
// Keep glyph declarations and ranges in ui_icons.h in sync with this subset.
namespace FontAwesome7Data {
inline constexpr char kSolidCompressedBase85[] =
    "7])#######ML[1_'/###Kn6+>%epo%Ql#v#haKT9s$X_9sr'##sh(##a&xe=@aA1aVQ'##JJw9);vA0FP<,EO[v&##^,'##l?>UCwjrt%@,%##Ynh--f'TqLPKA,;UXn92)e^w'C3n0F"
    "D58[7&cX&#x+Qe$e[X=B46hl/wiYW-F/5I$w:]=BfAM%uA'u92C60R<o5FiFkXvQNR7J&,isU5/>LN`<#WajL(U<;$'2G>#FPndFj?s>I.MZ1F##laGoS=b=xm.:CEY<Q/XJ/*#Ye5`s"
    "la*`sRsJL9j0lB$qsl.2v/#s./?[<$k[Vo(656lO/6(<-$Jw@'IDeH<Kk]#vdvSk,n5rY$NSpWQ;T0')nKn$#JCR`%8a($#X9F&#/jd(#[C,+#2tI-#_Mh/#5(02#bWM4#82l6#eb39#"
    ";<Q;#iu4Y#>F7@#kvTB#APsD#n*;G#DZXI#q4wK#HkGN##QxP#Y%Gu#c&h^#[20iFsN@qCm=wb%1Nnh2`&^G3f]UA5_#K,3]u><-v*i&OB@8+O8B/f3x.ZD4Z*]D4:%w`4Phw`4%>)a4"
    "5/@]-%`jC&cUWC&2_NeNCFA+OZ.<i2%6K)4xN]>-CrN^-1DALc939fNcKJ+OL**M2t'jD4kroF-J<wT-Pb^_-nn?F[6qaeN_L/J3*R/a477%r7AL(a4I/qg-%mf[B9*teN5fQL2HMClL"
    "s7737E5>C5pkn+H5-xF-OgRl1EAYC5F)9+4w.odFiCN88Jua>-wcT)48qQl11C570k^T%J$'4RDCKlmBw=r@0Ge/b4b8EVClf9fFE;:'R40(V%H->>#'K,'#N2>>#5YSiB29758BhFlo"
    "C/bM9dYQGVgwu%tR:M5ST5cs$Zx'ZPN]p/:AGu,;r#&w,2Tl/US+O-)x](b<Bjk6/omgWmi<iNgLO4@>WiEOK7`M-2hspb)4;]BKuwGc%#&9?KgV6^OTkU]tpUYDNk-a>T'9Ic%2bY-M"
    "n(9rM/?+nO*ruXU8qx$4LaeFN-_N3MZ9:V%<R'%4@sW_O&AddGIfFF)#&_PS$j8vKR]tvK<mZ^S1AgEslWIeG?a<gOe-2^Oi7_Rs#6;].IiW]s&I[`%4^ibn5G)S%2Tigtov_tOx9dRj"
    "3B@C;igEc%+3w3;(F4^OQarKjuk<9[FZDFD+&O;Mu<Hc%;Fe6Nx,Yp77M%hcQ/&gL@OWnNd_vtLKwsrM%gf]t$%XrL2`3uLC.<;Rvj=8NgJ@/QreQ2h1<x88.Rw'S06wc%klEcRhq9ZG"
    "Y%p8I-fHW$ji<cR&8;aNPbwuL=SB%4^'iJs40L-2kSuh'6P#hPL:ta%OpZbrasq9Mj6?c%A9P-Q=?u]tH_jX$g*V:VI*DmS)VB%Tl3F3/Al=Qs/&hATmQOZLf?+c2Tivd)<IwiOSH*NK"
    "=K6#TjkVX,=%U]tA?E=([<YTV;pad%Ocst,=*SY-2AE=(d-Y*@i(jd%QVWX,CI0I$9?27<(t5^,1][n3]3,:?`3R[P2@2^T`,SrO&)AuL1G%qJej$_$`KBWMk.rPfJAAKQULr]K1]t`$"
    "8,TCJ-:?Z>?w`:MBF[:M?dk*%qWU:MMkLa$DM#DJFV[&F,i0[K2e4HQoGhh$'G:9MVQe2Kt'C@K)xMjOb3Jf$?d?BSv8f2K_FTdQIphaRB>,d$3kFdQaO]&FYTI$T%uT)SWOOk$_J@+R"
    "+P7^Oc/;2P$&Do_rL>pNIjjd%$X1sQ.+Z]TK:<mHC&ZAT?W3d%[tD;drY^k^D?)pO&Q3x^%]PgO(-a:D(Nc^%%^R>D'#CN'`QIF;spGdI`=0b%IMaIC`,wQNdt0b%N*t;M@t?jT;Ynkt"
    "a&#VDuusoOd5YpOahK1Yd+2g%E,u^$172qSk%]JQ@MO`S[>.bRi5IIsCtigt;VToOP]rUVHf[`%0NU]t$IG</EPI4X92.xLsRfrs.4Vh)jZ3i0uG.iOiYH`%(gcC3#(/rJxpDd%aF#]T"
    "M'^Ds-j%]$uO>xT-io`ts82[$:0=oT?XGpRsx*cRZZLr$i3V_Oq&n]OQce=Mg[bF+1vvmOZk[#LCqw`tdmlkGL]RfG=@r_t'?OfG)DOlWCX`Gsd1`^SmqY=UVqKr)e>Di88#FdX=>M-2"
    ";:`k)cPJ3/r$@W^8JL<q^Vt]Oh_asatQm<ca'gs-eMs]O`d6aI/eg=:@W^@TX@Oa%#E8?KFl%EEe%31^3Hsn8Wn8WRaQSFeWao*%l]v0K.c?BSg;*O=)fIf$uIpDS0`7^OQO7^K5k7+M"
    "h+gjO.c(]K'cqj)'/#[1Z@d<e#DGIDmG,iOqbnktKva8^`$B08%hSq)bdC.YE-ZpL&cM56a]rUVH`R`%bk9)IBCX#GQ8InOYbeOX857xLh6q`t[n$mORn3;M/WAo.s.KkOdqTb%91e6N"
    "qxGZ%.2Mf$EKuHQ#,vDNh]eJQ_=ZXj2k*,R/qHc%]T^SN<gO&XGc[(q3wNGRQiXU%SMq$F:-TXH-q2fH2Xt+HDj([$g5tcVva&jH9NwVU6*Yqt_9WqM:+%uL&#*]$>@@YL*fJsQZYnbR"
    "H@6VY1[[+R49*d%*/V[4Dcpp$2G%]4P-`h9%(L%Bnmf]%DqLg$r,)*BJ7WB1_Zi`aR)jpOd'f_o'%c`'ae:p79,J`tgR6sI[$WZRd$,s/<qIZU.[EvOk`VB'tpsaOL4Bwm5ZdkK=`CxK"
    "]4QTM/Sc@Kc16V$p@:ERqQ_b%e;imOMt]DsQ^h_$%`5&T2f7^OXeI^K=tRFMgwQ^t<^-%4#;B6so_SrLMZZq$7ol-I(&Z8e;]&oOA-kOX12n*M)`8.It[Gc%LKADsPbQ]1*Hk;-Erko$"
    "3vTW-%TB&m?<HhO4<<j$2r961gIOQ'rZVSsL+cZK<:@^Kt<,ft?Ea#L)`GaS<kVmO8-jd%=1kq6RHAI$`_@QK<G(]K*tRFM.G*^-Rxa*7G0`*7rKqpM]j(wK<sd^Sk6_*7+xjd%ou[*7"
    "rTAI$w4,TS)P'`SD#i_%Nb[nRvgV_O;F%S%Avt`O0K&VDnKrd%1/x`$:h]KPsf#HMhfwJQe*bKnk4OgI6I4i%bZGFspsmCsX-l-$Kmo]tn5M%+;UxrO24;78VYNJMLU?jijTaaOhMwUM"
    "$bmc%aoF/LCr:AK'@]:-g^HH+D)q)90OXQ'H</.1#O$+N'k=n0/G2u$N@a20tOs]O,YoMB02je-<VDUokPorM`&2mO4b*cR29*d%AVAp7;^OQBc4VRs96/EBKJ;n/M1+N'Bx/ism5j+&"
    "&+E<A*`wIO/kPa$mFp<U>X(B=W3`^S-SPsL^t,`O4r:_t8t#s/E7?eO40fd$jvl[.@eLg$r8V9.PYIjO-KNB-qS3:M0d'$L/UMMi&w$vQw60HN5lu%1(1b^-4R,1%v*K(JE?GX8j=^au"
    "2W]mOvZSFe0f:_tQgpoO.f&VD8t6LF8CGc%ZJ7+%AC*T.9^WRsh)H%.Vok@92Lf%u?^9TT'wS0N+hcZ-rNe$0r@q]O%$1TOYtdS'+Dkxs[5TvL3/5@Kg4nU?&,CaO:9'`Shk'b%7;>@K"
    "+ht]t^ffe$+u2NOj;FjKkuEKQBq%[sTa7+MHw_PKH-K8N8pe$Txb9dR%])Ws-M4dRfHXvLf?+c2r2-Re>.K0%o&_btnQw'()^st,=R7`t_2L<fb[h5%lWFIsu*m*7qxB788Kjt(HgNHM"
    "PfSFM@R#A'A[7Q'/dUO8g6Ncs8*F<-#Kf;%-A]q)@QK<;uFMf$Z9bVMpr6^OLh;uL:X8kO'0Kf$Hd_*R,S7^OIa%cRiD2mOQP,V$jF/HVu.ZU$LM^Q?3p'j)(.dc[+5AU)dqPGje*E+]"
    "u%&[hOPJGj>6xFY70SSsVrVn:fj,a&s2_bt/F,x'%WWX,VTAI$SsRhtcrRnR,fm<-L)I:&GGR,2_1i;;2jt`OwLUR%%u1W%pxI`t$Jf`tZ:BgLNh%S%Xankt.f]`tt#1C&iX2Z%>U6l)"
    "GcJ`$7s7sUvl+^b)djYPp+OGR,_04/+=Wt(HpAX%G'ZZ$8x6UMZ-2TIUAoO,YMvrsH2Q&Sv75WLnq>a$nAwaIeP6^O.-N@?NwX<Lhd/w5TXfFIR*tZLkg;a$o`RnOAs<vl#U;S?=ZlTV"
    "w/F(lm%1*S-:V:VT5tp$m@gWUn0m)3eT^Xqa<tNL._Md%s4Av>%lY_OP(DM3M?#lOx77^Oqpnxa'3RjO1SG1P5h)W%pV;U1H$94OF[Jx?s:gOO6%Xb.L92l$x2cq?slG)/9/p]O[+w<("
    "p3v0,=tBN'.$s*,(MJuO,q0iX0gIc%MWT=Vc^^Dsv9)#((pDX(<*:oFlIGc%UElCIife)<@7GnCn-I.Q5%>4Qoo<fOtKtB-Ll?x-nYs_P`R4`PS'DN:e[k05.LrE@LJB.Z#?Bb`8T,ES"
    ";*Ic%_-o>Llf6^O#W4g:)i,qpf9Gne`3fs-YaqM9):]`t(=va5^2;c)8a7$7'Bu$4qXY_OlSpe=I$B;O+9u`:(M?/;$vcs-=4,:;dgNJMgM4hLG]Sug;w+TRex(*%=I^Ms:EtnLZfCE'"
    "Q,@Q/Cmqb)-<<OgQM0fO?\?O%9BJWdO]SDfOJs#P=NZ$k%a+N7c,`]Ds-`/HsGQse)g<NCllV;m0:<W+4dL3^OQ_nhr>(OgrSYGuO29:c)9c<S,DT5=>3@anS-4S33Z:>h)1#+*BCB5^O"
    ";>`d>YHFP;1ktKj[e:Esu&@_t_%r]OP>5,`D0B;e[G#F5`v@;:&,a*.JcT=&arRk$O3LaOfEtWo&lk7*<;e`Od#/gL[4ia%pcJpIbsWnR5&:aO3h*cR5BEd%gc3(SIN8T@+<eTctUX$g"
    "358k7N^#U7AV7Z7N/8c7o6;'SXVwBSk2ddIeCBb%v`<FI(fFpRK>*?Tl?tj/x,)xpPRa,qYa<V/24,tnWqr`/$_3Mal]eYLn$$c%6+%:Moo6^O]Z3QLM(N-2*n@C<MjGaS:-Ic%]VGf$"
    "cEXvL#c+TRCF[[%NA4K&s`wZRWT1X%4I9i$u7#g)10fu-]e(J8N5S`t_aJg%;2r<cD@/=8*7S`tss-J(KW)Rqt*:wOR2MR'cj@=>E8:lF8/`_%B/_hLL_qRFA9WY$,nBT%m^jci7;vkE"
    "cM8kOj?Lb%a8imO)44jg%BxcRbD.bRGj.n$AeWjObDY)N.pUrEKOIf$aIKi::wa>-:'GW%[w`aOa2Kmt6c7bO^s$YL;Qjd%?fDDs6([W$a?jI1GKg)S<-Ic%OXN#./*,dNtkQ^tweqt&"
    "0,_e$&HfER.(&7qoBpg8u+0kO'@gC/1O$gL/x?uL)emt$KThi$J]q[-bP1TT+Ra;;F2:BY*ugWM4'ad%B4<M-Du;M-eMo+/`YeMKa$ALY$KeKY8b[nRj*p#I/6WRsrbme%]JHf$hp#9N"
    "M+]5]Y^FSN^sulOLR$ktLwap.=YwnRF0E#eX1>a$7W+C.a_'b%5&6T.P&r]O,HRj'2e(gL-7D:'6/w`OCI>r'(?%n4KJTv)$&###SY0##42_RlodPir0P5##ZedYmZn8NN0+[=l/7u%O"
    "=$*W%&il8.OYr.L8%)da%/5##_1jV7*fbA#171^#KTi*N?xSfLZf_@-YcOkL[V+kLJ/,GMqGkGNxgj3M3r6AO`JM2Nlb`.Mk+m<-TxH]-R3n0#sMwA#_FPq;.)<X(aj6o#/nRfLC=%m/"
    "PDc>#RK*1#)[Jj-R3n0#=F7##%####=Zv%+*JNfL[-sv#<4th#6gPF%m$,t7rMSF#:uD`s;GfB.%ULS734cA#ase34$wo*%@j9I$SMc##+6>##_RFgL]U$lL0=`T.VP?(#o3xU.3xL$#"
    "?A`T.eCW)#IsG<-N2:W.7)]-#Rq*c3V5$C#'c/*#Xst.#e)1/#I<x-#ni+S0lj9'#ZqB'#bbrmLQqkRMFtt)#U0f-#H)m<-]-uPS'KG&#4jq@-[Lx>-4Z5<-H?:@-6C2&.]U4oLmX#.#"
    "ZZO.#xh_$]2,:kL(^r'#-9q'#,nXoL.xXrLhS=RMZRG&#o%2MMi=UkLjOqkL+V.(#C'wT-%xhH-sYM1.F37/PE%[lL*i?lL2wVE-D[oCPJk?lLh_tn-aqIRjK5YY#&>uu#6g5K)'5>>#"
    "*+q>$iM,F%]#m)#iAP##]*l.qnm$0qE.H3q2eo5qQpU7q?hv;q='nCq`1)GqKW_Jq7)tLqvV:RqDiYbqNWhfqAg7)rnYD4s1^_vuae3B-iU3B-7oj#.AH7cPoWsYPeX1)N#%1oMJJk2("
    "?$g.(.@a-(@TR)(vgC((C&6$('b5r'2T#r'HOqn'p7S+Me/:i'#NfX'`b-S'/qnH'UF(;&`<^M%OF%'MFd?58Y+_A9;j<R.Z4*##";

} // namespace FontAwesome7Data
